<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
		<Compile Remove="Common\Interfaces\**" />
		<Compile Remove="Features\Auth\Commands\RegisterChef\**" />
		<EmbeddedResource Remove="Common\Interfaces\**" />
		<EmbeddedResource Remove="Features\Auth\Commands\RegisterChef\**" />
		<None Remove="Common\Interfaces\**" />
		<None Remove="Features\Auth\Commands\RegisterChef\**" />
	</ItemGroup>
	<ItemGroup>
		<Folder Include="Features\Auth\Mappings\" />
		<Folder Include="Features\Auth\Queries\" />
		<Folder Include="Common\Behaviours\" />
		<Folder Include="Features\Notifications\Commands\" />
		<Folder Include="Features\Orders\Queries\" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="16.2.0" />
		<PackageReference Include="FluentValidation" Version="12.1.1" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
		<PackageReference Include="Hangfire.Core" Version="1.8.24" />
		<PackageReference Include="Hangfire.SqlServer" Version="1.8.24" />
		<PackageReference Include="MediatR" Version="14.2.0" />
		<PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.11" />
		<PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.10" />
		<PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="10.0.10" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
		<PackageReference Include="System.Security.Cryptography.Xml" Version="8.0.4" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\ChefNear.Domain\ChefNear.Domain.csproj" />
		<ProjectReference Include="..\ChefNear.Shared\ChefNear.Shared.csproj" />
	</ItemGroup>
</Project>